
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import MainContractArtifactJson from '../../target/aztec_adapter_l2-Main.json' with { type: 'json' };
export const MainContractArtifact = loadContractArtifact(MainContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Main;
 */
export class MainContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, MainContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, MainContract.artifact, wallet) as Promise<MainContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<MainContract>(PublicKeys.default(), wallet, MainContractArtifact, MainContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<MainContract>(publicKeys, wallet, MainContractArtifact, MainContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MainContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MainContract['methods'][M]>
  ) {
    return new DeployMethod<MainContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MainContractArtifact,
      MainContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MainContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MainContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'aztec_l1_adapter' | 'owner_of_leaf_index' | 'root_history' | 'giga_root'> {
      return {
        aztec_l1_adapter: {
      slot: new Fr(1n),
    },
owner_of_leaf_index: {
      slot: new Fr(3n),
    },
root_history: {
      slot: new Fr(4n),
    },
giga_root: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'aztec_l1_adapter' | 'owner_of_leaf_index' | 'root_history' | 'giga_root'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** initialize(aztec_l1_adapter: struct) */
    initialize: ((aztec_l1_adapter: EthAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** receive_root(root: field, root_type: integer, bridge_message_leaf_index: field) */
    receive_root: ((root: FieldLike, root_type: (bigint | number), bridge_message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_leaf(leaf_index: integer, leaf_value: field) */
    update_leaf: ((leaf_index: (bigint | number), leaf_value: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
