[package]
name = "aztec_adapter_l2"
type = "contract"
authors = ["Jimjim Valkema"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v2.0.3", directory="noir-projects/aztec-nr/aztec" }